### ISSUE TITLE
Failed to activate the open-terminal-here package

### ISSUE THREAD

**Issue by hayao56** [Flynsarmy/atom-open-terminal-here#10]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.190.0
**System**: Mac OS X 10.10.3
**Thrown From**: [open-terminal-here](https://github.com/Flynsarmy/atom-open-terminal-here) package, v0.5.0

### Stack Trace

Failed to activate the open-terminal-here package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
    at Object.module.exports.activate (/Users/gorohayakawa/.atom/packages/open-terminal-here/lib/open-terminal-here.coffee:18:32)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:225:19)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:206:30
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:152:15)
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:199:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:435:21)
    at /Applications/Atom.app/Contents/Resources/app/src/package-manager.js:419:29
    at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app/src/config.js:302:16)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:414:19)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:395:46)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "disabledPackages": [
      "recent-files"
    ]
  },
  "open-terminal-here": {}
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.2.3
bracket-matcher, v0.73.0
git-diff, v0.54.0
git-plus, v4.4.13
git-projects, v1.13.0
open-terminal-here, v0.5.0

# Dev
No dev packages
```

**Comment by Flynsarmy** [comment]
Fixed in https://github.com/Flynsarmy/atom-open-terminal-here/pull/13
